# Generated by Django 4.2.3 on 2023-07-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Project Name')),
                ('points', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True, verbose_name='Due Date')),
                ('users', models.ManyToManyField(blank=True, to='projects.users')),
            ],
        ),
    ]
